export const IPC_CHANNELS = {
  DB: {
    GET_SUBJECTS: 'db:getSubjects',
    GET_SUBJECT_BY_ID: 'db:getSubjectById',
    CREATE_SUBJECT: 'db:createSubject',
    UPDATE_SUBJECT: 'db:updateSubject',
    DELETE_SUBJECT: 'db:deleteSubject',
    GET_TASKS: 'db:getTasks',
    GET_TASKS_BY_SUBJECT: 'db:getTasksBySubject',
    CREATE_TASK: 'db:createTask',
    UPDATE_TASK: 'db:updateTask',
    DELETE_TASK: 'db:deleteTask',
    GET_ASSESSMENTS: 'db:getAssessments',
    GET_ASSESSMENTS_BY_SUBJECT: 'db:getAssessmentsBySubject',
    CREATE_ASSESSMENT: 'db:createAssessment',
    UPDATE_ASSESSMENT: 'db:updateAssessment',
    DELETE_ASSESSMENT: 'db:deleteAssessment',
    QUERY_TABLE: 'db:queryTable',
    CREATE_TABLE_RECORD: 'db:createTableRecord',
    UPDATE_TABLE_RECORDS: 'db:updateTableRecords',
    DELETE_TABLE_RECORDS: 'db:deleteTableRecords',
    INVOKE: 'db:invoke',
  },
  SYNC: {
    START: 'sync:start',
    STATUS: 'sync:status',
    GET_PENDING_COUNT: 'sync:getPendingCount',
    GET_LAST_SYNCED: 'sync:getLastSynced',
    SET_ONLINE_STATE: 'sync:setOnlineState',
    ON_SYNC_PROGRESS: 'sync:onProgress',
    ON_SYNC_COMPLETE: 'sync:onComplete',
    ON_SYNC_ERROR: 'sync:onError',
    ON_STATUS_CHANGE: 'sync:onStatusChange',
  },
  AUTH: {
    GET_TOKEN: 'auth:getToken',
    SET_TOKEN: 'auth:setToken',
    CLEAR_TOKEN: 'auth:clearToken',
    GET_USER: 'auth:getUser',
    STORE_SESSION: 'auth:storeSession',
    CLEAR_SESSION: 'auth:clearSession',
    GET_LAST_USER: 'auth:getLastUser',
  },
  APP: {
    GET_VERSION: 'app:getVersion',
    GET_PLATFORM: 'app:getPlatform',
    OPEN_EXTERNAL: 'app:openExternal',
    CHECK_UPDATE: 'app:checkUpdate',
    APPLY_UPDATE: 'app:applyUpdate',
    QUIT: 'app:quit',
    MINIMIZE: 'app:minimize',
    MAXIMIZE: 'app:maximize',
    OPEN_FOCUS_TIMER: 'app:openFocusTimer',
    UPDATE_FOCUS_TIMER: 'app:updateFocusTimer',
    CLOSE_FOCUS_TIMER: 'app:closeFocusTimer',
  },
  PLATFORM: {
    IS_ONLINE: 'platform:isOnline',
    ON_ONLINE_CHANGE: 'platform:onOnlineChange',
    GET_PATH: 'platform:getPath',
  },
} as const

export type IpcChannels = typeof IPC_CHANNELS
